[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
poem = "3.1.11"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
solana-client = "1.15.2"
solana-sdk = "1.15.2"
tokio = { version = "1.45.1", features = ["full"] }
